### ISSUE TITLE
Error building on raspberry pi b+

### ISSUE THREAD

**Issue by jozydapozy** [Schnouki/spop#36]
I'm running `sudo ./build_and_run` on my raspberry pi b+ and now 'm getting this error:

	Running CMake to regenerate build system...
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/pi/spop/build
	[  4%] Built target spop_audio_ao
	[  8%] Built target spop_audio_oss
	[ 12%] Built target spop_audio_sox
	[ 16%] Built target spop_plugin_awesome
	[ 48%] Built target spop_plugin_mpris2
	[ 52%] Built target spop_plugin_notify
	[ 56%] Built target spop_plugin_savestate
	[ 60%] Built target spop_plugin_scrobble
	[ 64%] Building C object CMakeFiles/spopd.dir/src/commands.c.o
	/home/pi/spop/src/commands.c: In function ‘_uri_image_cb_image_data’:
	/home/pi/spop/src/commands.c:1069:17: error: initialization makes integer from pointer without a cast [-Werror]
	cc1: all warnings being treated as errors
	CMakeFiles/spopd.dir/build.make:77: recipe for target 'CMakeFiles/spopd.dir/src/commands.c.o' failed
	make[2]: *** [CMakeFiles/spopd.dir/src/commands.c.o] Error 1
	CMakeFiles/Makefile2:340: recipe for target 'CMakeFiles/spopd.dir/all' failed
	make[1]: *** [CMakeFiles/spopd.dir/all] Error 2
	Makefile:113: recipe for target 'all' failed
	make: *** [all] Error 2

I had to manually install `cmake`. Is this a cmake version issue?

**Comment by jozydapozy** [comment]
A workaround for me was to remove the -Werror flag (line 226) in the `CMakeLists.txt` which simply ignores this error.

**Comment by Schnouki** [comment]
Fixed, thanks!
