### ISSUE TITLE
search

### ISSUE THREAD

**Issue by mph070770** [Schnouki/spop#48]
Hi All,

Can anyone advise how I can perform a search where the list of returns results can be filtered? For example. how do I:

search my playlists
get the top tracks for a particular artist
search for a specific track

I assumed something list seach "artist: ed sheeran" would work but it doesn't seem to do what I expect.

Can anyone advise on the correct syntax?

Thanks
Martin

**Comment by Schnouki** [comment]
To show your playlists: "ls" (shows the whole list).
Top tracks for a particular artist: not implemented, you can just search for all the albums and tracks from a specific artist. The syntax would be `artist:"ed sheeran"`. If you're doing it from a script, you can then sort tracks by their `popularity` attribute, but I'm afraid you'll have to do that yourself.

If you want a good example of a spop client, please have a look at dspop (also in the Git repository).

Cheers,
Thomas

**Comment by Schnouki** [comment]
Ok, I read your mail and now I understand your questions a bit better. I'll add feature requests for the playlist search and tophit_tracks command, and I'll try to work on them when I have some time.
Thanks!
