### ISSUE TITLE
Search Gives {"error":"General transient error"}

### ISSUE THREAD

**Issue by irishwill2008** [Schnouki/spop#63]
When you connect and try do a search for lets say "Lion King", before it would work!
Today i now receive: {"error":"General transient error"} for the output?

Why is this? Any help is appreciated.
Thank you.

**Comment by Schnouki** [comment]
It seems to work at the moment, so I'm closing this.

This may have been an issue with the Spotify service. Or it's just that they are slowly but surely starting to break compatibility with libspotify, which is the core of spop, but has been deprecated by Spotify. Sorry about that.

**Comment by irishwill2008** [comment]
Hi there,

The issue is now back again and has been happening for at least a week! I decided not to post in case it fixed itself like before but it doesnt seem to be happening. Hopefully you can check and see whats happening. Cheers
