### ISSUE TITLE
Latest Spotify UI enhancments appear to have killed libspotify

### ISSUE THREAD

**Issue by janui** [Schnouki/spop#68]
Hi there,
In May 2018 I received an email from Spotify announcing their new improved user interface. spop stopped working almost immediately. spop still logs in correctly but no longer returns anything useful to play.
Looks like the already in 2015 depreciated libspotify has final stopped working.
Are there any plans to re-engineer spop to use an alternative library like librespot?
janui

**Comment by Schnouki** [comment]
Hi janui,

Honestly I'm not sure... I created spop when I had *way* more free time that I have now... So I can't tell for sure that I'll be able to work something out.
Librespot sure looks interesting, but a few years ago they said they were not really interested in providing a replacement for libspotify, and they're more focused on Spotify Connect.
I'll probably try to do something in the future, but I'm afraid I really can't promise anything about that...
Best,
Thomas

**Comment by janui** [comment]
Hello Thomas,
Thanks for the fast responce. Understand about time, avalable, required, for other things,... :-)
janiu
